tools:
    external_code_coverage: true
    php_mess_detector:
        enabled: true
        extensions:
            - php
        command: phpmd
        filter:
            paths: {  }
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
        config:
            rulesets:
                - codesize
    php_analyzer:
        enabled: false
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        extensions:
            - php
        command: phpcs
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
    php_pdepend:
        command: pdepend
        configuration_file:   ~
        suffixes:
            - php
        excluded_dirs:
            - vendor
        enabled: true
